version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=12345
      - DB_NAME=tasks
      - DB_PORT=5432

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=tasks
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: